### ISSUE TITLE
As a User I want to see the ASM Mammalian Diversity Database appear as a data source

### ISSUE THREAD

**Issue by jhpoelen** [GlobalNamesArchitecture/dwca_hunter#18]
As a User I want to see the ASM Mammalian Diversity Database appear as a data source in https://resolver.globalnames.org and related services . 

It appears that the https://mammaldiversity.org resource is being used among mammal researchers. 

I was able to download attached dump ```mammal.json.gz``` using ```curl 'https://mammaldiversity.org/species-account/api.php?q=*' -H 'User-Agent:' | gzip > mammal.json.gz``` . 

Note that the User-Agent was somehow needed. 

See https://github.com/globalbioticinteractions/globalbioticinteractions/issues/446 . 

FYI @tigerhawkvok @n8upham

[mammal.json.gz](https://github.com/GlobalNamesArchitecture/dwca_hunter/files/4093869/mammal.json.gz)

**Comment by dimus** [comment]
@jhpoelen just saw it, will add it in the next few days

**Comment by dimus** [comment]
@jhpoelen, got the data to resolver.globalnames.org
I am making updates and new imports of data these few weeks, when I am done I'll move the data to index.globalnames.org as well and publish the data dump

**Comment by jhpoelen** [comment]
@dimus excellent  - please also note that @n8upham et al. are starting an easier to use mammal diversity database at https://github.com/mammaldiversity/mammaldiversity.github.io/tree/master/_data . However, this is still very much a work in progress, so I'll let @n8upham , a mammal diversity database curator, chime in on whether to use this version.

**Comment by jhpoelen** [comment]
I just did a search on ```Enhydra lutris``` via resolver.globalnames.org, and found a match with a MDD taxon of same name with taxon id 549 . However, in MDD, the taxon id https://mammaldiversity.github.io/#7750 (or https://mammaldiversity.org/species-account/species-id=7750) is associated with the taxon. How did you populate the taxon ids?

**Comment by dimus** [comment]
>I just did a search on Enhydra lutris via resolver.globalnames.org, and found a match with a MDD taxon of same name with taxon id 549
hm, I guess I should use their ``internal_id`` instead of ``id``

```json
    "1721": {
      "id": "549",
      "species_authority": "Linnaeus",
      "canonical_sciname": "Enhydra lutris",
      "image": "species_photos/2bccdb0a8b47b4e59a0b56c800790173.jpg",
      "notes": "",
      "authority_year": "{\"1758\":1758}",
      "parens_auth_genus": "0",
      "internal_id": "7750",
      "major_type": "placentalia",
      "genus": "enhydra",
      "taxon_author": "",
      "parens_auth_species": "0",
      "genus_authority": "Linnaeus",
      "deprecated_scientific": "",
      "subspecies": "",
      "simple_linnean_group": "eutheria",
      "linnean_order": "carnivora",
      "source": "iucn",
      "species": "lutris",
      "taxon_credit": "",
      "taxon_credit_date": "",
      "common_name": "Sea Otter",
      "major_subtype": "boreoeutheria",
      "linnean_family": "mustelidae",
      "simple_linnean_subgroup": "weasels / otters",
      "citation": "",
      "image_credit": "J G Hall 1975",
      "image_license": "{\"CC BY-NC 4.0\":\"https:\\/\\/creativecommons.org\\/licenses\\/by-nc\\/4.0\\/legalcode\"}",
      "entry": "",
      "common_name_source": "iucn",
      "image_caption": "Side view, in kelp bed.",
      "species_authority_citation": "",
      "genus_authority_citation": "",
      "simple_linnean_group_alt": "placentalia",
      "linnean_subfamily": "lutrinae",
      "linnean_tribe": "",
      "juniorSynonym": "0",
      "synonymOf": "",
      "TaxonomyNotes": "",
      "TaxonomyNotes_Citation": "",
      "extinct": "0",
      "geo_distribution": "marine",
      "authority_fullcitation": "linneaus, c von. 1758. systema naturae per regna tria naturae: secundum classes, ordines, genera, species, cum characteribus, differentiis, synonymis, locis. (10th ed.). stockholm: laurentius salvius.",
      "authority_link": "https://biodiversitylibrary.org/page/25033865",
      "MDDv1": "1",
      "newSppSinceMSW3": "0",
      "IfNew_category": "",
      "IfNew_evidenceCitation": "",
      "IfNew_evidenceAuthors": "",
      "IfNew_evidenceYear": "",
      "IfNew_evidenceLink": "",
      "IfNew_nameCitation": "",
      "IfNew_nameAuthors": "",
      "IfNew_nameYear": "",
      "IfNew_nameLink": "",
      "genusTransfersinceMSW3": "0",
      "IfTransfer_oldSciName": "NA",
      "IfTransfer_oldIUCN_ID": "",
      "IfTransfer_evidenceCitation": "",
      "dwc": {
        "scientificName": "Enhydra lutris",
        "genus": "enhydra",
        "subspecificEpithet": "",
        "order": "carnivora",
        "specificEpithet": "lutris",
        "vernacularName": "Sea Otter",
        "family": "mustelidae",
        "namePublishedIn": "",
        "higherClassification": {
          "cohort": "eutheria",
          "magnaorder": "placentalia",
          "superorder": "boreoeutheria",
          "list": "eutheria|placentalia|boreoeutheria"
        },
        "scientificNameAuthorship": {
          "genus": "Linnaeus, 1758",
          "species": "Linnaeus, 1758"
        },
        "taxonRank": "species",
        "class": "mammalia",
        "taxonomicStatus": "accepted",
        "dcterms:bibliographicCitation": "Enhydra lutris (ASM Species Account Database #7750) fetched 2020-05-24T18:03:01+0000",
        "dcterms:language": "en",
        "dcterms:modified": "2020-05-24T18:03:01+0000",
        "dcterms:license": "https://creativecommons.org/licenses/by-nc/4.0/legalcode"
      }
    },
```

**Comment by n8upham** [comment]
Hi @dimus and @jhpoelen -- Thanks for flagging this.  Yes, we are working on both a new web infrastructure for hosting the updated taxonomy, the CSV for which will always be located here as "mdd.csv" : https://github.com/mammaldiversity/mammaldiversity.github.io/blob/master/_data/mdd.csv

So rather than setting up the GlobalNames resolver to point to our old API, I'd suggest setting things up to point to this file location, which should be constant.

> I am very interested in obscure outdated names that are some kind of synonyms to the currently accepted ones. Will your database include such information?
@dimus, yes we are collecting & curating large amount of synonym data as part of this ASM effort, but its not currently ready for prime-time, and so no visible via this CSV download.  Our next full version of the taxonomy (v2) will contain this information though

**Comment by dimus** [comment]
@jhpoelen I "hackishly" changed ID value  from `id` to `internal_id`.

I am desperately need to get verification speed to >= 1000 names/sec on average, so I am starting a new project where I will try to do outlink generation data a bit more precise

https://github.com/gnames/gnames/blob/68d9b5046df7c68cf95eece5e1d0988b1aa611d5/protob/protob.proto#L70

IDs in databases is quite a mess, and are just plain missing totally or partially sometimes. So I think I got to output that takes care of the inconsistencies 

```json
        {
          "data_source_id": 184,
          "data_source_title": "ASM Mammal Diversity Database",
          "gni_uuid": "557bc7f6-673b-58d1-8cfb-2832050d898a",
          "name_string": "Enhydra lutris Linnaeus, 1758",
          "canonical_form": "Enhydra lutris",
          "classification_path": "Animalia|Chordata|Mammalia|Carnivora|Mustelidae|Enhydra|Enhydra lutris",
          "classification_path_ranks": "kingdom|phylum|class|order|family|genus|",
          "classification_path_ids": "",
          "taxon_id": "7750",
          "edit_distance": 0,
          "imported_at": "2020-05-25T21:26:16Z",
          "match_type": 2,
          "match_value": "Exact match by canonical form",
          "prescore": "3|0|0",
          "score": 0.988
        }
      ]
    }
```

**Comment by dimus** [comment]
@n8upham it is great that you are going to have a permalink for the data! I can see that format of your CSV did not stabilize yet, so I think it makes sense for me to wait for some time until you feel it is not going to change anymore.

I do have a few questions/suggestions/requests about the CSV:

- blank field. I suspect that csv was generated on a Windows machine and you introduced blank line to fight a zero-length BOM character. I would suggest to remove the BOM character instead.

- fields names. Would it be possible to have fields consistent in capitalization. I think most common for CSV files is so-called PascalCase when words are concatenated and each word is capitalized like in ``ScientificName``. A camelCase is common for JSON outputs ``scientificName``, and, to my knowledge, snake_case is common for variables in some languages like Ruby ``scientific_name``. 

- metadata. Would be great to also have a URL to some metadata, with version and release date.

- utf-8, I think you did change encoding to UTF-8 already, thats great!

- vernacular names. Would be great to have them back

- synonyms. I want them :)

**Comment by dimus** [comment]
Closing this one for now, we can continue talking...

**Comment by n8upham** [comment]
Thanks for those tips @dimus, and for your interest in our project -- definitely all those things are in progress, we just aren't quite ready for primetime yet as I said.  We did, however, get the BOM character issue solved.  I'll work to standardize some PascalCase names too (I hadn't heard of those specific names for this before, cool!)

Metadata will be coming with our Zenodo DOIs on the official releases, and both vernacular names (ported in from HMW1-9) and synonyms will be coming back with our v2.0 of the MDD, likely in the next 1-2 months.  All the best
--n

**Comment by dimus** [comment]
great to know @n8upham, and I am happy I could help a little bit. Great to know about Zenodo DOI! I have a few command-line tools that might be of some help for quality control. They work on windows pretty well:
https://gitlab.com/gogna/gnparser
https://github.com/gnames/gnverify
