### ISSUE TITLE
Import IOC World Bird List

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/dwca_hunter#21]
@ccicero, @dustymc, I started new imports, and will notify you for every ticket, this way it will be easier for you to see their status.
IOC World Bird List - https://www.worldbirdnames.org/ioc-lists/master-list-2/

**Comment by ccicero** [comment]
Awesome, thanks Dmitry!

**Comment by dimus** [comment]
IOC World Bird List is now at resolver.globalnames.org, I will move it to index.globalnames.org as well when I renew all databases.

This resource needs some manual work, because the data are versioned, and there is no permanent 'the latest' link. I also decided to convert from Excel to CSV manually, as I need to do a bit of manual involvement anyway.
I did normalized authors accoring to the majority of authorships in GN, for example

``(Baird, WM & Baird, SF, 1843)`` becomes ``(W. M. Baird & S. F. Baird, 1843)``
