### ISSUE TITLE
Import Clements Checklist

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/dwca_hunter#22]
FYI @dustymc  @ccicero
Clements Checklist - https://www.birds.cornell.edu/clementschecklist/download/

**Comment by dimus** [comment]
@ccicero, I am looking at the data, and it looks like there is no 'real' id included, is a match by canonical form with classification metadata sufficient?

**Comment by ccicero** [comment]
I'm not sure what that means. Can you give an example? Thanks!

**Comment by dimus** [comment]
For example, Arctos has `Bubo bubo` and Clements has `Bubo bubo`. Arctos wants to tell for `Bubo bubo` record, that a record with the name-string exists in Clements also. Are you just stating the fact that the name exists in Clements, or you want to present some kind of an outlink to it?

**Comment by dimus** [comment]
Imported to resolver.globalnames.org, index.globalnames.org will be done after adding/updating all datasets

http://resolver.globalnames.org/data_sources/187
