### ISSUE TITLE
taxon ids of unknown provenance in Mammal Species of the World v3  

### ISSUE THREAD

**Issue by jhpoelen** [GlobalNamesArchitecture/dwca_hunter#25]
When inspecting the json results for matches of ```Enhydra lutris``` against Mammal Species of the World (data source id 174), taxon_id 28576 and internal_id 14001090  is found (see below). However, it appears that the internal_id 14001090  is the identifier that the Mammal Species of the World exposes to link to their taxon pages (e.g., https://www.departments.bucknell.edu/biology/resources/msw3/browse.asp?id=14001090). For some reason, the taxon_id 28576 cannot be found in any of the Mammal Species of the World data products.

This suggests that the (current) internal_id are suitable to be used as taxon ids (incl. in path ids hierarchy).

  |  
-- | --
data_source_id | 174
data_source_title | "The Mammal Species of The World"
gni_uuid | "3096feea-1216-5f59-ab70-fcff3492cef6"
name_string | "Enhydra lutris Linnaeus 1758"
canonical_form | "Enhydra lutris"
classification_path | "Mammalia\|Carnivora\|Caniformia\|Mustelidae\|Lutrinae\|Enhydra\|Enhydra lutris"
classification_path_ranks | "class\|order\|suborder\|family\|subfamily\|genus\|species"
classification_path_ids | "1\|25367\|27246\|28538\|28539\|28575\|28576"
taxon_id | "28576"
local_id | "14001090"
edit_distance | 0
imported_at | "2018-08-04T20:50:18Z"
match_type | 2
match_value | "Exact match by canonical form"
prescore | "3\|0\|0"
score | 0.988
29 |

**Comment by dimus** [comment]
We need an explicit field, something like "templateID" I think. If it is empty, we do not know how to construct outlink, if it is filled -- the outlink can be constructed. I am going to introduce it into the next version of the reconciliation/resolution tool

https://github.com/gnames/gnames/blob/e28865e935e06ba2f4b4dbd9dc842519ac96511c/protob/protob.proto#L66

**Comment by dimus** [comment]
On a second thought, we just return outlink as is

https://github.com/gnames/gnames/blob/41bcf0875398aa0916f7834e84fe499214f68009/protob/protob.proto#L65

**Comment by dimus** [comment]
Fixed in https://github.com/gnames/gnames

http://verifier.globalnames.org/api/v1/verifications/Enhydra+lutris?pref_sources=174
