### ISSUE TITLE
Import name-strings from Museum of Comparative Zoology Db (Harvard)

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/dwca_hunter#27]
@chicoreus

**Comment by chicoreus** [comment]
Note that the MCZ's database is known as MCZbase, with that capitalization.    Some relevant links: Source is under doi:10.5281/zenodo.891420 at github.com/MCZbase/MCZbase, schema at github.com/MCZbase/DDL  IPT resource with the data is at: http://digir.mcz.harvard.edu/ipt/resource?r=mczbase with doi:10.15468/p5rupv

**Comment by chicoreus** [comment]
Also note @heliumcell

**Comment by dimus** [comment]
I made a quick reconciliation of names to whole GN and got the following matches distribution:

Exact matches: 194188
Fuzzy matches: 24463
PartialExact matches: 42402
PartialFuzzy matches: 1723
NoMatch: 4645

https://uofi.box.com/shared/static/u64iow4ql0vo6td85edly7vswqvsnrrs.csv

**Comment by dimus** [comment]
Import worked

@Archilegt the search for 'Cryptus heathi' does return MCZ result now
http://resolver.globalnames.org/data_sources/186

There are no IDs, so I generated fake ones (I do the same for Arctos). There is no taxonomic relationship between the names, but I decided to leave classification, as it might help people to orient themseleves better with search results.

Let me know if you want to improve on something! I will close the ticket for now, but can reopen it if there are improvements needed.

**Comment by dimus** [comment]
The data did not percolate to https://index.globalnames.org. I will update its database when I inish updating old and importing new data sets.

**Comment by chicoreus** [comment]
Note that Arctos and MCZbase have internal surrogate numeric primary keys for Taxonomy table entries, but the externally exposed identifier for the taxon record is the URI https://mczbase.mcz.harvard.edu/name/  followed by the taxon name without the authorship, e.g. https://mczbase.mcz.harvard.edu/name/Cryptus%20heathi

**Comment by chicoreus** [comment]
We'll (@heliumcell and I) probably make a request to update the textual metadata description of the resource https://resolver.globalnames.org/data_sources/186 will review with MCZ collections operations and get back to you.

**Comment by chicoreus** [comment]
Spot checking the quick reconciliation report above, noted these three names reported as NoMatch which look like they do have matches.  Issues with the report?

Esox lucius Linnaeus, 1758
Isistius brasiliensis (Quoy and Gaimard, 1824)
Trachinotus falcatus (Linnaeus, 1758)

**Comment by dimus** [comment]
Good catch @chicoreus, I am importing a few more datasets, and will fix this for all of them in a few days.

**Comment by dimus** [comment]
I rebuilt the index, all should work now at resolver.globalnames.org
