### ISSUE TITLE
Update Index Fungorum

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/dwca_hunter#33]
Paul Kirk sent a new dump of Index Fungorum, it has to be converted to DWCA and imported.

**Comment by Adafede** [comment]
Could it be that "species" is missing at the end of the classificationRanks?

```
 "classificationPath": "Fungi|Ascomycota|Sordariomycetes|Hypocreales|Nectriaceae|Fusarium fujikuroi",
 "classificationRanks": "kingdom|phylum|class|order|family|",
```

**Comment by dimus** [comment]
yes, the rank of a name is not provided in the IF dump file.

**Comment by Adafede** [comment]
As you see the initial data and know Paul Kirk, do you think I could add it manually after retrieval or would you advise against it?

**Comment by dimus** [comment]
Paul would not mind for sure, Ill try to remember to ask him to add rank next time
