### ISSUE TITLE
Add "Discover Life bee species guide and world checklist"

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/dwca_hunter#53]
From @seltmann 
https://zenodo.org/record/5738043

**Comment by dimus** [comment]
@seltman, @jpoelen, I did hit a problem when trying to import Discover Life's Bees checklist. Looks like a significant number of `providedId`s are not unique, for example:

https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri,HAS_ACCEPTED_NAME,https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri

https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,,SYNONYM_OF,https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri

running the following command, allows to find all non-unique numbers of the first field (providedId) I get 959 Ids that repeat more than once:

```bash
xsv select 1 discoverlife-Anthophila.csv |sort |uniq -d
```
https://github.com/BurntSushi/xsv

I am not sure how to import the data correctly.

**Comment by dimus** [comment]
@seltmann, @jhpoelen, I am trying to create DWCA file from your data. I did hit a problem when trying to import Discover Life's Bees checklist. Looks like a significant number of providedExternalIds are not unique, for example:

https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri,HAS_ACCEPTED_NAME,https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri

https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,,SYNONYM_OF,https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri

running the following command, allows to find all non-unique numbers of the first field (providedId) I get 959 Ids that repeat more than once:

xsv select providedExternalId discoverlife-Anthophila.csv |sort |uniq -d

And

xsv select providedExternalId data.csv |sort |uniq -D|wc -l

Tells that altogehter there are 2043 rows with non-unique Ids

https://github.com/BurntSushi/xsv

How should I deal with such rows?

**Comment by seltmann** [comment]
@dimus Just to clarify, the 2043 rows you are finding that do not have 949 non-unique IDs are they all synonyms of themselves as in your example? 

https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,,SYNONYM_OF,https://www.discoverlife.org/mp/20q?search=Pseudapis+neumayeri,Pseudapis neumayeri,"Bossert and Pauly, 2019",species,Animalia | Arthropoda | Insecta | Hymenoptera | Halictidae | Pseudapis neumayeri

Note that on the [DiscoverLife webpage](https://www.discoverlife.org/mp/20q?act=x_checklist&guide=Apoidea_species&flags=HAS:) where the data came from this is exactly how the data was presented. See the screenshot below from the webpage

![Screen Shot 2022-01-14 at 1 36 11 PM](https://user-images.githubusercontent.com/1044474/149588932-57eddacd-e713-4939-9bb5-ce1a93d24ed8.png)


.

**Comment by dimus** [comment]
Thank you Katja for the explanation.

I am not sure what such a synonymy statement tries to tell. Can you help me to understand what does it mean? Different circumstcriptions by different taxonomists would be one idea, but then there is no references to these taxonomists.

I guess for such records there are two possible ways of dealing with them. Both go to the same goal --
to keep identifiers unique.

1.  Discard synonymy records that are self-referential.
2.  Keep all the records but produce better new identifiers. This is definitely more time consuming, as it would require remapping of all the synonymy records to new identifiers.

Normalization of datasets before aggregation to gnverifier database is quite time consuming and it pushes other GN projects down the line. Because of that I would ask you to help me and rebuild the data-set keeping only unique identifiers.

**Comment by seltmann** [comment]
@dimus I also do not know what it means and I think it is a mistake in producing the online checklist. I suggest discarding synonymy records that are self-referential.

**Comment by dimus** [comment]
@seltmann to be able to use your dataset I would need a cleaner data, at the moment the main problem is identifiers that point to several records. If you can remove duplicates, I will try to import again, and hopefully there are no other show stoppers.

**Comment by jhpoelen** [comment]
@dimus Good to hear from you! Note that I haven't yet updated to associated Zenodo pub @ https://zenodo.org/record/5738043 . @seltmann  would you prefer getting a new version on https://zenodo.org/record/5738043 so that @dimus can index a relatively stable version of DiscoverLife bees?

**Comment by dimus** [comment]
@jhpoelen, @seltmann, where can I find your updated data? The only link I have is the one from Zenodo.

**Comment by jhpoelen** [comment]
@dimus thanks for asking. 

I am still waiting for @seltmann to verify the latest results and prepare a new version of the pub:

Seltmann, Katja, & Poelen, Jorrit. (2021). Tab and comma delimited versions of Discover Life bee species guide and world checklist (Hymenoptera: Apoidea: Anthophila) (v55.1) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5738043

Thanks for being patient as we are working on this update.

**Comment by seltmann** [comment]
Hi @dimus @jhpoelen The zenodo publication is updated. Thank you!

Seltmann, Katja, & Poelen, Jorrit. (2022). Tab and comma-delimited versions of Discover Life bee species guide and world checklist (Hymenoptera: Apoidea: Anthophila) (v55.2) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.6147345

**Comment by dimus** [comment]
@seltmann, @jhpoelen thank you, all worked well this time 

https://verifier.globalnames.org/data_sources/202
